# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chase Sawyer
email: shadowimmage@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Chase Sawyer, developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shadowimmage.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: shadowimmage

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
permalink: /blog/:year/:month/:day/:title
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-coffeescript
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock